// types describe the actions happening on the app 
export const  ADD_PRODUCT = "ADD_PRODUCT";
export const  ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const  ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";


export const PRODUCTS_DOWNLOAD = "PRODUCTS_DOWNLOAD";
export const PRODUCTS_DOWNLOAD_SUCCESS = "PRODUCTS_DOWNLOAD_SUCCESS";
export const PRODUCTS_DOWNLOAD_ERROR = "PRODUCTS_DOWNLOAD_ERROR";

export const GET_PRODUCT_DELETE = "PRODUCT_DELETE";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_ERROR = "PRODUCT_DELETE_ERROR";


export const GET_PRODUCT_EDIT = "GET_PRODUCT_EDIT";
export const START_EDIT_PRODUCT = "START_EDIT_PRODUCT";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
export const PRODUCT_EDIT_ERROR = "PRODUCT_EDIT_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";